### ISSUE TITLE
Extend README with Jenkins and Gradle description

### ISSUE THREAD

**Issue by debrecenics** [IncQueryLabs/MD_plugin_skeleton#17]
Provide more details in the README about the Gradle and Jenkins technolgoies and their usage in this skeleton project.

**Comment by beothy** [comment]
I have created wiki pages about
- [Build and CI](../wiki/Build-and-CI)
- [MD Plugin Test Environment](../wiki/MD-Plugin-Test-Environment)
- [Command Line Actions](../wiki/Command-Line-Actions)

**Comment by Akiira** [comment]
Just wanted to say thanks for writing that documentation. I have been wanting to set up a CI server and unit tests for my plugins for a while now and you just helped me make it happen.
