### ISSUE TITLE
Sort out IModelManipulations

### ISSUE THREAD

**Issue by bergmanngabor** [IncQueryLabs/MD_plugin_skeleton#8]
In the current master, the example model transformations declare and initialize a field `extension IModelManipulations manipulation`, but never actually use it. This is pointless.

We should either:
 - toss out the `IModelManipulations` if we feel it is not relevant for MD (is it?), or
 - make sure that the actual transformation rules do in fact go through `manipulation` (see soon-to-be-uploaded pull request)

**Comment by ujhelyiz** [comment]
I'd go for removing the model manipulations here. The main reason for this is that elementarty model manipulation steps are on a wrong abstraction level to handle transactions correctly - the entire transformation should be run as a single transaction, as it could be undo-ed in a single step.

**Comment by bergmanngabor** [comment]
Done.
